# Generated by Django 4.2.2 on 2023-06-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end',
            field=models.IntegerField(null=10),
            preserve_default=10,
        ),
    ]
