# Generated by Django 4.2.2 on 2023-06-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_offer_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(null=10),
            preserve_default=10,
        ),
    ]
